# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 13:32
from __future__ import unicode_literals

import Posts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('0', 'IT Equipment'), ('1', 'Non-IT Equipment'), ('2', 'Furnitures and Fixtures'), ('3', 'Aircons'), ('4', 'Lab Equipment')], max_length=1)),
                ('status_type', models.CharField(choices=[('0', 'unattended'), ('1', 'in progress'), ('2', 'done')], max_length=1)),
                ('description', models.TextField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('pic_report', models.FileField(blank=True, upload_to=Posts.models.report_upload_path)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
