# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('0', 'IT Equipment'), ('1', 'Non-IT Equipment'), ('2', 'Furnitures and Fixtures'), ('3', 'Aircons'), ('4', 'Lab Equipment')], default='0', max_length=1),
        ),
    ]
