# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_auto_20170527_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_title',
            field=models.TextField(default='Report Init', max_length=20),
        ),
    ]
