# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_report_report_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_title',
            field=models.TextField(max_length=20),
        ),
    ]
