# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0004_auto_20170527_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='location',
            field=models.CharField(choices=[('0', 'AS Bldg.'), ('1', 'Undergrad Bldg.'), ('2', 'Library'), ('3', 'Kiosks'), ('4', 'Mgt. Bldg.'), ('5', 'Admin Bldg.'), ('6', 'High School')], default='0', max_length=1),
        ),
    ]
