# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 07:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_report_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 27, 7, 52, 37, 437665, tzinfo=utc), verbose_name='date published'),
        ),
    ]
