# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 13:32
from __future__ import unicode_literals

import Profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_auto_20170527_0753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='owner',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(blank=True, upload_to=Profile.models.avatar_upload_path),
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
